from . import res_config_settings
from . import insight_scenario
from . import insight_task_schedule
from . import insight_session_message_template
from . import insight_user_session
from . import insight_session_switch_wizard
from . import project_project
from . import project_task
from . import insight_import_wizard
from . import hr_attendance
from . import hr_employee
